# Generated by Django 5.0.3 on 2024-03-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialist', '0004_alter_reviews_description'),
        ('specialization', '0001_initial'),
        ('user_app', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacilityAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user_app.user',),
        ),
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Poland', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('specialists', models.ManyToManyField(blank=True, null=True, related_name='specialist_facilities', to='specialist.specialist')),
                ('specialties', models.ManyToManyField(related_name='medical_facilities', to='specialization.specialization')),
                ('admins', models.ManyToManyField(related_name='medicalFacilityAdmin', to='medical_facility.medicalfacilityadmin')),
            ],
        ),
    ]
