# Generated by Django 5.0.3 on 2024-03-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
        ('specialization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='specializations',
        ),
        migrations.AddField(
            model_name='specialist',
            name='main_specialization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='specialization.specialization'),
            preserve_default=False,
        ),
    ]
