# Generated by Django 5.0.3 on 2024-03-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0002_remove_specialist_specializations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='specialist',
            name='number_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='consultation_scope',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_consultation_scope', to='specialist.specialist'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_education', to='specialist.specialist'),
        ),
        migrations.AlterField(
            model_name='foreign_languagese',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_foreign_languages', to='specialist.specialist'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_reviews', to='specialist.specialist'),
        ),
        migrations.AlterField(
            model_name='treateddisease',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_treed_disease', to='specialist.specialist'),
        ),
        migrations.AlterField(
            model_name='visit_type',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_visit_type', to='specialist.specialist'),
        ),
    ]
