# Generated by Django 5.0.3 on 2024-03-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0003_specialist_avg_rating_specialist_number_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='description',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
