# Generated by Django 5.0.3 on 2024-03-27 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_facility', '0002_alter_medicalfacility_phone_number_and_more'),
        ('specialist', '0005_alter_specialist_main_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(blank=True, default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='medical_facility.medicalfacility')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpecialistSlot', to='specialist.specialist')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_type', to='specialist.visit_type')),
            ],
        ),
    ]
