# Generated by Django 5.0.3 on 2024-04-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_facility', '0002_alter_medicalfacility_phone_number_and_more'),
        ('specialist', '0006_specialistslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistslots',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_facility_address', to='medical_facility.medicalfacility'),
        ),
        migrations.AlterField(
            model_name='specialistslots',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_slot', to='specialist.specialist'),
        ),
        migrations.AlterField(
            model_name='specialistslots',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_visit_type', to='specialist.visit_type'),
        ),
    ]
