# Generated by Django 5.0.3 on 2024-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=None, max_length=9),
            preserve_default=False,
        ),
    ]
