# Generated by Django 5.0.3 on 2024-04-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_first_name_alter_patient_last_name_and_more'),
        ('specialist', '0006_specialistslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visit_reservation', to='patient.patient')),
                ('reservation_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReservationInfo', to='specialist.specialistslots')),
            ],
        ),
    ]
